var mapped_tz = {
 "Pacific/Truk": "Pacific/Chuuk",
 "Pacific/Ponape": "Pacific/Pohnpei",
 "Atlantic/Faeroe": "Atlantic/Faroe",
 "Asia/Calcutta": "Asia/Kolkata",
 "Asia/Katmandu": "Asia/Kathmandu",
 "Africa/Asmera":"Africa/Asmara",
 "America/Buenos_Aires":"America/Argentina/Buenos_Aires",
 "America/Catamarca":"America/Argentina/Catamarca",
 "America/Coral_Harbour":"America/Atikokan",
 "America/Cordoba":"America/Argentina/Cordoba",
 "America/Indianapolis":"America/Indiana/Indianapolis",
 "America/Jujuy":"America/Argentina/Jujuy",
 "America/Louisville":"America/Kentucky/Louisville",
 "America/Mendoza":"America/Argentina/Mendoza",
 "Asia/Saigon":"Asia/Ho_Chi_Minh",
}
